### ISSUE TITLE
Script and download patches

### ISSUE THREAD

**Issue by forall** [dalgibbard/citrix_xenserver_patcher#43]
Hi,
I use your script for install patches for XS 6.x and it's work great, but I don't know why it download 
Starting patching...

Downloading: XS65E013.zip
Download Size: 14336251 Bytes Applying: XS65E0130%]
Uncompressing...
Internal Upload...
XE Error detected: The uploaded patch file already exists
uuid: e30c4671-54bb-4272-8ff8-a1276b705da2

Other question is, why it doesn't download patches XS61SP1005 and 1008, I see it on citrix updates site.

**Comment by dalgibbard** [comment]
I'll try testing the first issue myself shortly; but in the meantime, you mention patches XS61SP1005 + 1008 - are you sure these are the right ID's? As they would be for XS 6.1 rather than the 6.5 that you're currently running.

**Comment by dalgibbard** [comment]
OK so; I managed to track down the issue around XS65E013 without testing; the CTX page here: http://support.citrix.com/article/CTX201636 links to the CVE here: http://support.citrix.com/article/CTX201593 which links to the SP1 specific patch here: https://support.citrix.com/article/CTX201637 - even though the "includes the following previously released hotfixes" doesn't list this one... I guess it makes sense though, as this patch was released post-SP1 release.

Anyyyyway... Should be all good now since 254dda5 
Thanks to auto-exclusion loading, this should be in effect on your system already (unless you manage these manually in any way.)

I'll leave it open for you to report back before closing.

**Comment by forall** [comment]
Hi,
It's my mistake :-) I thought XS65SP1005,1008 I don't know why I wrote XS61 :-).
I check now a new version script and it's look good. All patches download and install correct, you can close this issue.

**Comment by dalgibbard** [comment]
Thanks!

**Comment by forall** [comment]
Hi,
Today I have another the same problem. Script want dowanload a patch for XS 6.5 version not for X6.5 SP1.

Downloading: XS65E014.zip
Download Size: 14335915 Bytes
   14335915  [100.00%]
Applying: XS65E014
Uncompressing...
Internal Upload...
Completed: 49601b62-2ae6-481e-a0f1-9135d96d8bb1

Applying Patch 49601b62-2ae6-481e-a0f1-9135d96d8bb1
Patch failed, code: 1
Command failed: /opt/xensource/bin/xe patch-apply
uuid=49601b62-2ae6-481e-a0f1-9135d96d8bb1
host-uuid=8c0f96ec-7dc8-4c8f-9a7f-2a7ae47bb949
Failed to apply patch: The patch precheck stage failed: the server is of an
incorrect version.
patch: 49601b62-2ae6-481e-a0f1-9135d96d8bb1 (XS65E014)
found_version: XS65ESP1 - Public Availability: XenServer 6.5 Service Pack 1
(SP1)
required_version: 6.5

Secondary validation check...
Patch apply failed for: XS65E014.xsupdate

**Comment by dalgibbard** [comment]
Whoops; sorry for the delay in sorting this one! Saw the message and then forgot to do it :) will sort it now.

**Comment by dalgibbard** [comment]
Fixed in 8364234

**Comment by dalgibbard** [comment]
Should take effect immediately, assuming no caching on consumer premises :)
